name: Build and Deploy defikarte.ch web

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        working-directory: ./web
        run: npm install

      - name: Build React App
        working-directory: ./web
        run: npm run build

      - name: Determine Deployment Path
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        id: deployment_path
        run: |
          if [ "${GITHUB_REF##*/}" == "main" ]; then
            echo "path=/home/$DEPLOY_USER/www/production.defikarte.ch" >> $GITHUB_ENV
          else
            echo "path=/home/$DEPLOY_USER/www/staging.defikarte.ch" >> $GITHUB_ENV
          fi

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm -rf $path/*
            rsync -avz --delete ./web/build/ $path/
