name: Build and Deploy defikarte.ch web

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

env: 
  DEPLYOMENT_PATH: "${{ github.ref == 'refs/heads/main' && './www/production.defikarte.ch' || './www/staging.defikarte.ch' }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        working-directory: ./web
        run: npm install

      - name: Build React App
        working-directory: ./web
        run: npm run build

      - name: Clean target directory on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo ${{ env.DEPLYOMENT_PATH }}
            rm -rf ${{ env.DEPLYOMENT_PATH }}/*

      - name: Copy build artifacts to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./web/dist/
          target: ${{ env.DEPLYOMENT_PATH }}
          strip_components: web/dist/
